[tool.poetry]
name = "codezine-scraper"
version = "0.1.0"
description = ""
authors = ["yoshi-d-24"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scrapy = "^2.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
